/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Year = IDL.Variant({
  'y1' : IDL.Null,
  'y2' : IDL.Null,
  'y3' : IDL.Null,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : IDL.Text,
  'year' : Year,
});

export const idlService = IDL.Service({
  'addNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Note], []),
  'getNotes' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Note)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Year = IDL.Variant({
    'y1' : IDL.Null,
    'y2' : IDL.Null,
    'y3' : IDL.Null,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : IDL.Text,
    'year' : Year,
  });
  
  return IDL.Service({
    'addNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [Note], []),
    'getNotes' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Note)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };